from http.server import BaseHTTPRequestHandler
import json
import os
import tempfile
import shutil
import requests
from pathlib import Path
from ..utils import setup_path

# Add project root to sys.path
setup_path()

from src.git_manager import GitManager

class handler(BaseHTTPRequestHandler):
    def do_OPTIONS(self):
        """Handle CORS preflight requests."""
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()

    def do_POST(self):
        try:
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)
            data = json.loads(post_data.decode('utf-8'))
            
            repo_name = data.get('repoName')
            token = data.get('token')
            design = data.get('design', {})
            plan = data.get('plan', {})
            handoff_content = data.get('handoffContent', '')
            
            if not repo_name or not token:
                self.send_error(400, "Missing repoName or token")
                return

            # 1. Create GitHub Repository
            headers = {
                'Authorization': f'token {token}',
                'Accept': 'application/vnd.github.v3+json'
            }
            
            # Check if it's a user or org repo (simple user repo for now)
            api_url = 'https://api.github.com/user/repos'
            payload = {
                'name': repo_name,
                'private': True, # Default to private for safety
                'description': f"Generated by Devussy: {design.get('project_name', 'Project')}"
            }
            
            print(f"[github/create] Creating repo {repo_name}...")
            response = requests.post(api_url, headers=headers, json=payload)
            
            if response.status_code not in [200, 201]:
                error_msg = response.json().get('message', 'Unknown error')
                print(f"[github/create] Failed to create repo: {error_msg}")
                self.send_response(400)
                self.send_header('Content-Type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                self.wfile.write(json.dumps({"error": f"GitHub API Error: {error_msg}"}).encode('utf-8'))
                return

            repo_data = response.json()
            clone_url = repo_data['clone_url']
            # Inject token into URL for authentication: https://token@github.com/...
            auth_clone_url = clone_url.replace('https://', f'https://{token}@')
            
            print(f"[github/create] Repo created: {clone_url}")

            # 2. Create Temp Directory and Files
            with tempfile.TemporaryDirectory() as temp_dir:
                temp_path = Path(temp_dir)
                print(f"[github/create] Working in temp dir: {temp_path}")
                
                # Write README
                with open(temp_path / "README.md", "w", encoding="utf-8") as f:
                    f.write(f"# {design.get('project_name', 'Devussy Project')}\n\n")
                    f.write(f"Generated by Devussy.\n\n")
                    f.write(f"## Description\n{design.get('description', 'No description provided.')}\n")

                # Write Design
                with open(temp_path / "project_design.md", "w", encoding="utf-8") as f:
                    f.write(design.get('raw_response') or json.dumps(design, indent=2))

                # Write Plan
                with open(temp_path / "development_plan.md", "w", encoding="utf-8") as f:
                    f.write(json.dumps(plan, indent=2))
                    
                # Write Handoff
                if handoff_content:
                    with open(temp_path / "handoff_instructions.md", "w", encoding="utf-8") as f:
                        f.write(handoff_content)

                # Write Phases
                phases_dir = temp_path / "phases"
                phases_dir.mkdir(exist_ok=True)
                
                if plan and 'phases' in plan:
                    for phase in plan['phases']:
                        p_num = phase.get('number', 0)
                        p_title = phase.get('title', f'Phase {p_num}').replace(' ', '_').lower()
                        p_filename = f"phase_{p_num}_{p_title}.md"
                        
                        content = f"# Phase {p_num}: {phase.get('title', 'Untitled')}\n\n"
                        content += f"## Description\n{phase.get('description', '')}\n\n"
                        
                        if 'steps' in phase:
                            content += "## Steps\n"
                            for idx, step in enumerate(phase['steps']):
                                content += f"### {idx+1}. {step.get('title', 'Step')}\n"
                                content += f"{step.get('description', '')}\n\n"
                        
                        with open(phases_dir / p_filename, "w", encoding="utf-8") as f:
                            f.write(content)

                # 3. Git Operations
                try:
                    git = GitManager(temp_path)
                    git.init_repository()
                    git.add_remote("origin", auth_clone_url)
                    git.commit_changes("Initial commit by Devussy")
                    git.push("origin", "master") # Try master first
                except Exception as e:
                    # Try main if master fails (GitHub default changed)
                    try:
                        print(f"[github/create] Push to master failed, trying main... ({e})")
                        git.push("origin", "main")
                    except Exception as e2:
                        print(f"[github/create] Git push failed: {e2}")
                        raise e2

            # Success Response
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            
            response_data = {
                "status": "success",
                "data": {
                    "repoUrl": repo_data['html_url'],
                    "message": "Repository created and code pushed successfully!"
                }
            }
            self.wfile.write(json.dumps(response_data).encode('utf-8'))

        except Exception as e:
            print(f"[github/create] Error: {e}")
            import traceback
            traceback.print_exc()
            self.send_error(500, str(e))
